### ISSUE TITLE
First Release Roadmap

### ISSUE THREAD

**Issue by bloha** [fructo/native-application-deno#1]
# First Release Roadmap

## Connection management
- [ ] All outgoing messages must be transparent for clients.
- [ ] A client should be able to specify a new server's port on the fly. In this case, all open connections must be gracefully reopened with the new port.

## Application's Settings management
- [ ] Clients should be able to request default settings.
- [ ] Clients should be able to request saved settings.
- [ ] Clients should be able to save settings.

### Download process management
- [ ] Clients should be able to pause a specified download process.
- [ ] Clients should be able to resume a paused download process.
- [ ] Clients should be able to abort a specified download process.
- [ ] Clients should be informed about the download progress.

### Download logic 
- [ ] Clients should be able to download a single album.
- [ ] Clients should be able to download all albums of a specified user.
- [ ] Clients should be able to download favorite albums of a specified user.
- [ ] Clients should be able  to download search results.
- [ ] Clients should be able to download tagged albums.

### Upload process management
- [ ] Clients should be able to pause a specified upload process.
- [ ] Clients should be able to resume a paused upload process.
- [ ] Clients should be able to abort a specified process.
- [ ] Clients should be informed about the upload progress.

### Upload logic
- [ ] Clients should be able to upload a single album.

## Network flow
- [ ] Clients should be able to manage the network flow on the fly.

## Platform support
The project should take into account different file systems.

- [ ] Full support of Linux (ext4).
- [ ] Full support of Windows 10 (NTFS).
